apiVersion: apps/v1
kind: Deployment
metadata: 
  name: llm-runner
  namespace: staging
  labels:
    app: llm-runner

spec:
  replicas: 1
  selector:
    matchLabels:
      app: llm-runner
  
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%

  template:
    metadata:
      name: llm-runner
      labels:
        app: llm-runner
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: staging
                operator: In
                values:
                - true
      serviceAccountName: runner-service-sa
      containers:
      - name: llm-runner
        image: DOCKER_IMAGE
        imagePullPolicy: Always
        env:
        - name: ENVIRONMENT
          valueFrom:
            secretKeyRef:
              name: qna-secrets
              key: ENVIRONMENT
        - name: COMPLETED_TEXTRACT_QUEUE_URL
          valueFrom:
            secretKeyRef:
              name: qna-secrets
              key: COMPLETED_TEXTRACT_QUEUE_URL
        - name: LLM_IMAGE_NAME
          valueFrom:
            secretKeyRef:
              name: qna-secrets
              key: LLM_IMAGE_NAME
        - name: LLM_OUTPUT_QUEUE_URL
          valueFrom:
            secretKeyRef:
              name: qna-secrets
              key: LLM_OUTPUT_QUEUE_URL
        ports:
        - containerPort: 6000
          name: llm-runner
        resources:
          requests:
            memory: "200Mi"
            cpu: "200m"
          limits:
            memory: "4000Mi"
            cpu: "2"
