apiVersion: apps/v1
kind: Deployment
metadata:
  name: textract-runner
  namespace: staging
  labels:
    app: textract-runner

spec:
  replicas: 1
  selector:
    matchLabels:
      app: textract-runner
  
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%

  template:
    metadata:
      name: textract-runner
      labels:
        app: textract-runner
    spec:
      containers:
      - name: textract-runner
        image: DOCKER_IMAGE
        imagePullPolicy: Always
        ports:
        - containerPort: 6000
          name: textract-runner
        # resources:
        #   requests:
        #     memory: "512Mi"
        #     cpu: "256m"
        #   limits:
        #     memory: "512Mi"
        #     cpu: "256m"
