apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: runner-service-role
  namespace: staging
rules:
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["create", "get", "list", "watch", "delete"]
