apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: runner-service-role-binding
  namespace: production
subjects:
  - kind: ServiceAccount
    name: runner-service-sa
    namespace: production
roleRef:
  kind: Role
  name: runner-service-role
  apiGroup: rbac.authorization.k8s.io
